<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <UseSystemDrawing>true</UseSystemDrawing>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FlaUI.Core" Version="5.0.0" />
    <PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.62.0" />
    <ProjectReference Include="..\Metis.Core\Metis.Core.csproj" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
