<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <UseSystemDrawing>true</UseSystemDrawing>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Lulu</AssemblyName>
    <RootNamespace>Lulu.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lulu.Core\Lulu.Core.csproj" />
    <ProjectReference Include="..\Lulu.AI\Lulu.AI.csproj" />
    <ProjectReference Include="..\Lulu.Data\Lulu.Data.csproj" />
    <ProjectReference Include="..\Lulu.Windows\Lulu.Windows.csproj" />
  </ItemGroup>
</Project>
